apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: backup-target
  namespace: longhorn-system
value: s3://longhorn-backups@us-east-1/longhornlab
---
apiVersion: longhorn.io/v1beta2
kind: Setting
metadata:
  name: backup-target-credential-secret
  namespace: longhorn-system
value: longhorn-s3-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: longhorn-s3-secret
  namespace: longhorn-system
type: Opaque
data:
  AWS_ACCESS_KEY_ID: SGRrak1BcFA0anpDMjlLNHNQa3I=
  AWS_SECRET_ACCESS_KEY: WHhPUjJKSTlqWWlwNzNmUGU4dXl6T01mWEE2QmRVdVk4d2M3V21WYQ==
  AWS_ENDPOINTS: aHR0cHM6Ly9zMy5icnlubmhhcnJpc29uLmNvbQ==