apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: mynewvmnet
  namespace: default
spec:
  config: >-
    {"cniVersion":"0.3.1","name":"mynewvmnet","type":"bridge","bridge":"mgmt-br","promiscMode":true,"vlan":1234,"ipam":{}}
