apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: untrusted
  namespace: default
spec:
  config: >-
    {"cniVersion":"0.3.1","name":"untrusted","type":"bridge","bridge":"mgmt-br","promiscMode":true,"vlan":4321,"ipam":{}}
